services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/usr/src/roomie_backend/media
      - admin_volume:/usr/src/roomie_backend/static
  web:
    build: ./roomie_backend
    command: gunicorn roomie_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./roomie_backend/:/usr/src/roomie_backend/
      - media_volume:/usr/src/roomie_backend/media
      - admin_volume:/usr/src/roomie_backend/static
    expose:
      - 8000
    depends_on:
      - db
      - daphne
  daphne:
    build: ./roomie_backend
    command: daphne --bind 0.0.0.0 -p 8002 roomie_backend.asgi:application
    ports:
      - 8002:8002
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=roomie

volumes:
  postgres_data:
  media_volume:
  admin_volume:
